### ISSUE TITLE
Runtime Error - While importing 'run', an ImportError was raised

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-flask-htmlx-mkit#1]
On windows, the manual build leads to an import error. Steps to reproduce the problem:

- Clone the project
- Create VENV
- Install deps: 
  - `pip3 install -r requirements.txt` 
- Set up the env:
  - `export FLASK_APP=run.py`
  - `export FLASK_ENV=development`
- Start the app or the CLI 
  - `flask run`
  - `flask shell` 

Both commands bumps import error (full log):

```log
$ flask run
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app '.\\run.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'run', an ImportError was raised.
```

**Comment by b3nhard** [comment]
**Bug fix: Import error on windows [https://github.com/app-generator/sample-flask-htmlx-mkit/issues/1](url)**

Entry file was not fully implemented.

**Commit : [https://github.com/app-generator/sample-flask-htmlx-mkit/commit/c7e2e675e3572b97136cdc5f432a357aed7248f9](url)**
